apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:4.4.15
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGODB_INITDB_ROOT_PASSWORD
          value: admin
        volumeMounts:
        - name: storage
          mountPath: /data/db
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - mongo --eval "db.adminCommand('ping')"
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      
