version: '3'
services:
  flask:
    image: flask-docker-image
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - FLASK_ENV=development
      - PORT=5000
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
  mongodb:
    image: mongo:4.4.15
    ports:
      - "27019:27017"
    expose:
      - "27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    volumes:
      - type: bind
        source: ./data
        target: /data/db
